version: "2"
services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      MYSQL_DATABASE: station_api_dev
      MYSQL_USER: station_api_dev
      MYSQL_PASSWORD: station_api_dev
      MYSQL_HOST: db
    restart: always
    links:
      - db
  db:
    image: mysql@sha256:1c224b6270c6a02f9e7eb9e4ca6486d3466f12be7390c0c0b6e6f908ea1a0346
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: station_api_dev
      MYSQL_USER: station_api_dev
      MYSQL_PASSWORD: station_api_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
